title = "benchmark parameters"

[debug]
number.of.features = [[10, 25, 50],
                      [10, 25, 50],
                      [10, 25, 50],
                      [10, 25, 50]]
number.of.planning.units = [[10, 25, 50, 100, 1000],
                            [10, 25, 50, 100, 1000],
                            [10, 25, 50, 100],
                            [10, 25, 50]]
formulation = ["unreliable", "unreliable", "reliable", "reliable"]
blm = [0, 0, 5, 5]
occupancy.probability = 0.9
replicates = 1
amount.target = 0.2
space.target = 0.5
time.limit = 7200

[release]
number.of.features = [[10, 25, 50],
                      [10, 25, 50],
                      [10, 25, 50],
                      [10, 25, 50]]
number.of.planning.units = [[10, 25, 50, 100, 1000],
                            [10, 25, 50, 100, 1000],
                            [10, 25, 50, 100],
                            [10, 25, 50]]
formulation = ["unreliable", "unreliable", "reliable", "reliable"]
blm = [0, 0, 5, 5]
occupancy.probability = 0.9
replicates = 10
amount.target = 0.2
space.target = 0.5
time.limit = 7200
