title = "benchmark parameters"

[debug]
number_of_features = [[10, 15, 20],
                      [10, 15, 20],
                      [10, 15, 20],
                      [10, 15, 20]]
number_of_planning_units = [[10, 20, 30],
                            [10, 20, 30],
                            [10, 20, 30],
                            [10, 20, 30]]
formulation = ["unreliable", "unreliable", "reliable", "reliable"]
blm = [0, 5, 0, 5]
occupancy_probability = 0.9
replicates = 4
amount_target = 0.2
space_target = 0.5
time_limit = 7200

[release]
number_of_features = [[10, 25, 50],
                      [10, 25, 50],
                      [10, 25, 50],
                      [10, 25, 50]]
number_of_planning_units = [[10, 25, 50, 100, 1000],
                            [10, 25, 50, 100, 1000],
                            [10, 25, 50, 100],
                            [10, 25, 50]]
formulation = ["unreliable", "unreliable", "reliable", "reliable"]
blm = [0, 5, 0, 5]
occupancy_probability = 0.9
replicates = 10
amount_target = 0.2
space_target = 0.5
time_limit = 7200
