title = "case-study 1 parameters"

[debug]
n.pc.layers = 2
pu.size = 50000
amount.target = 0.2
space.target = -10000
dp.quantile = 0.5
dp.number = 20
dp.bandwidth=[0.2, 0.2]
environmental.layer.resolution = 25000
thin.distance=10000
max.records=1000
mcp.percent=85
rarefy.cell.size=1000
species.names=['Dacelo leachii', 'Falco berigora', 'Ramsayornis modestus', 'Platycercus adscitus']
common.names=['Blue-winged kookaburra', 'Brown falcon', 'Brown-backed honeyeater','Pale-headed rosella']

[release]
n.pc.layers = 2
pu.size = 50000
amount.target = 0.2
space.target = 0.8
dp.quantile = 0.5
dp.number = 500
dp.bandwidth=[0.2, 0.2]
environmental.layer.resolution = 25000
thin.distance=10000
max.records=1e8
mcp.percent=85
rarefy.cell.size=1000
species.names=['Dacelo leachii', 'Falco berigora', 'Ramsayornis modestus', 'Platycercus adscitus']
common.names=['Blue-winged kookaburra', 'Brown falcon', 'Brown-backed honeyeater','Pale-headed rosella']

 
